import { MarkSectionSeen } from '../../../components/shell/MarkSectionSeen';
import { GenericStatusBadge } from '../../../components/ui/GenericStatusBadge';
import {
  Mail,
  Truck,
  CheckCircle2,
  RotateCcw,
  Plus,
  type LucideIcon,
} from 'lucide-react';
import { Card, CardBody } from '../../../components/ui/card';
import { Button } from '../../../components/ui/button';
import { PageHero } from '../../../components/layout/PageHero';
import { serverApi } from '../../../lib/api';
import { StageBadge } from '../../../components/outbound-mail/StageBadge';
import { DispatchQueuedButton } from '../../../components/outbound-mail/DispatchQueuedButton';
import { ResendLetterButton } from '../../../components/outbound-mail/ResendLetterButton';
import type { OutboundMailStage } from '@heartlink/api-contract';

export const dynamic = 'force-dynamic';

interface PipelineStage {
  key: OutboundMailStage;
  label: string;
  caption: string;
  icon: LucideIcon;
  tone: string;
  hoverBorder: string;
}

const PIPELINE: PipelineStage[] = [
  {
    key: 'queued',
    label: 'Queued',
    caption: 'Ready to send',
    icon: Mail,
    tone: 'text-warning bg-warning-tint',
    hoverBorder: 'hover:border-warning/50',
  },
  {
    key: 'in_transit',
    label: 'In Transit',
    caption: 'Handed to carrier',
    icon: Truck,
    tone: 'text-info bg-info-tint',
    hoverBorder: 'hover:border-info/50',
  },
  {
    key: 'delivered',
    label: 'Delivered',
    caption: 'Confirmed arrival',
    icon: CheckCircle2,
    tone: 'text-success bg-success-tint',
    hoverBorder: 'hover:border-success/50',
  },
  {
    key: 'returned',
    label: 'Returned',
    caption: 'Needs attention',
    icon: RotateCcw,
    tone: 'text-danger bg-danger-tint',
    hoverBorder: 'hover:border-danger/50',
  },
];

const LIFT =
  'transition-all duration-200 hover:-translate-y-0.5 hover:shadow-soft';

function formatDate(value: string) {
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(new Date(value));
}

export default async function OutboundMailPage() {
  const api = await serverApi();
  const summary = await api.getOutboundMailSummary();

  return (
    <div className="flex w-full flex-col gap-6 p-8">
      <MarkSectionSeen section="outboundMail" />
      {/* Hand-rolled heading and a hand-rolled button, so this screen sat at a
          different size, radius and disabled treatment from the rest. */}
      <PageHero
        eyebrow="Outbound Mail"
        title="Outbound Mail"
        description="Approval letters, welcome letters, and payment receipts queued for physical delivery."
        actions={
          <Button
            type="button"
            variant="primary"
            size="md"
            disabled
            title="Compose unlocks once PostGrid is connected"
          >
            <Plus aria-hidden className="mr-1.5 size-4" />
            Compose disabled
          </Button>
        }
      />

      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        {PIPELINE.map((stage, idx) => {
          const Icon = stage.icon;
          return (
            <Card
              key={stage.key}
              style={{ animationDelay: `${idx * 70}ms` }}
              className={`group animate-fade-up ${LIFT} ${stage.hoverBorder}`}
            >
              <CardBody className="gap-3 p-5">
                <div className="flex items-center justify-between">
                  <span
                    className={`inline-flex size-9 items-center justify-center rounded-md transition-transform duration-200 group-hover:scale-110 ${stage.tone}`}
                  >
                    <Icon aria-hidden className="size-[18px]" />
                  </span>
                  <span className="inline-flex min-w-9 items-center justify-center rounded-md bg-surface px-2 py-1 text-sm font-semibold text-text transition-colors duration-200 group-hover:bg-border">
                    {summary.counts[stage.key]}
                  </span>
                </div>
                <div>
                  <p className="text-sm font-semibold text-text">
                    {stage.label}
                  </p>
                  <p className="text-xs text-text-muted">{stage.caption}</p>
                </div>
              </CardBody>
            </Card>
          );
        })}
      </div>

      <Card
        className="animate-fade-up"
        style={{ animationDelay: '200ms' }}
      >
        <CardBody className="gap-4 p-6">
          <div className="flex items-baseline justify-between gap-4">
            <div>
              <h2 className="font-serif text-[17px] leading-[24px] text-text">
                Recent outbound queue
              </h2>
              <p className="mt-1 text-sm text-text-muted">
                Latest letters generated by the mailbox flow, grouped by delivery stage.
              </p>
            </div>
            <div className="flex items-center gap-3">
              <span className="text-xs text-text-muted">{summary.counts.all} total letters</span>
              <DispatchQueuedButton queued={summary.counts.queued} />
            </div>
          </div>

          {summary.recent.length === 0 ? (
            <div className="flex flex-col items-center gap-3 rounded-lg border border-dashed border-border px-6 py-14 text-center">
              <span className="inline-flex size-12 items-center justify-center rounded-full bg-accent-gold-tint ring-1 ring-accent-gold/25">
                <Mail aria-hidden className="size-5 text-accent-gold" />
              </span>
              <div className="max-w-md">
                <h3 className="font-serif text-lg text-text">No outbound letters yet</h3>
                <p className="mt-1 text-sm leading-6 text-text-muted">
                  This queue will populate once outside users start composing letters through the mailbox flow.
                </p>
              </div>
            </div>
          ) : (
            <div className="overflow-x-auto rounded-lg border border-border">
              <table className="w-full border-collapse text-left text-sm">
                <thead className="bg-surface-muted text-text-muted">
                  <tr>
                    <th className="px-4 py-3 font-medium">Recipient</th>
                    <th className="px-4 py-3 font-medium">Subject</th>
                    <th className="px-4 py-3 font-medium">Stage</th>
                    <th className="px-4 py-3 font-medium">Raw status</th>
                    <th className="px-4 py-3 font-medium">Created</th>
                    <th className="px-4 py-3 font-medium">
                      <span className="sr-only">Actions</span>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {summary.recent.map((item) => (
                    <tr key={item.id} className="border-t border-border align-top">
                      <td className="px-4 py-3">
                        <div className="font-medium text-text">{item.profileDisplayName || 'Unknown profile'}</div>
                        <div className="mt-1 text-xs text-text-muted">Thread {item.threadId.slice(0, 8)}…</div>
                      </td>
                      <td className="px-4 py-3">
                        <div className="font-medium text-text">{item.subject || 'Untitled letter'}</div>
                        <div className="mt-1 max-w-md text-xs leading-5 text-text-muted">
                          {item.preview || 'No preview available'}
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <StageBadge stage={item.stage} />
                      </td>
                      <td className="px-4 py-3">
                        <GenericStatusBadge status={item.deliveryStatus || 'queued'} />
                      </td>
                      <td className="px-4 py-3 text-text-muted">{formatDate(item.createdAt)}</td>
                      <td className="px-4 py-3 text-right">
                        {/* Only for letters that failed or came back. One still
                            queued or in transit is on its way, and re-queueing
                            it would post a second copy. */}
                        {item.stage === 'returned' ? (
                          <ResendLetterButton communicationId={item.id} />
                        ) : null}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          <div className="flex items-center justify-between gap-4 rounded-md border border-border bg-surface-muted px-4 py-3 text-sm">
            <div className="text-text-muted">
              {summary.deliveryConfigured ? (
                'Delivery provider is configured. Staff can monitor queue movement here.'
              ) : (
                <div className="space-y-2">
                  <div>
                    Delivery provider is not live yet. Queue visibility works, but staff actions stay disabled until client activation is complete.
                  </div>
                  {summary.deliveryIssues?.length ? (
                    <ul className="list-disc space-y-1 pl-5 text-xs">
                      {summary.deliveryIssues.map((issue) => (
                        <li key={issue}>{issue}</li>
                      ))}
                    </ul>
                  ) : null}
                </div>
              )}
            </div>
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
