import { ExpoConfig, ConfigContext } from 'expo/config';

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'HeartLink',
  slug: 'heartlink',
  version: '0.0.1',
  orientation: 'portrait',
  scheme: 'heartlink',
  userInterfaceStyle: 'automatic',
  newArchEnabled: true,

  // Generated by scripts/generate-brand-assets.mjs. Opaque square: iOS applies
  // its own squircle mask and renders black through any transparency.
  icon: './assets/icon.png',

  ios: {
    supportsTablet: true,
    bundleIdentifier: 'com.heartlink.app',
    infoPlist: {
      // Device testing points EXPO_PUBLIC_API_BASE_URL at the dev machine's LAN
      // address. Since iOS 14 the first connection to a local address raises a
      // permission prompt, and a prompt with no usage string is denied outright
      // - which surfaces only as fetch() failing, with no dialog to explain it.
      NSLocalNetworkUsageDescription:
        'HeartLink connects to the development API running on your local network.',
    },
  },

  android: {
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      // Matches the iOS icon ground so the app reads the same on both.
      backgroundColor: '#2E1240',
    },
    package: 'com.heartlink.app',
  },

  web: {
    bundler: 'metro',
    output: 'single',
    favicon: './assets/favicon.png',
  },

  // EAS project link. Written by hand because `eas init` cannot edit a dynamic
  // (.ts) config; spread `config.extra` first so expo-router's own `extra`
  // survives rather than being replaced.
  extra: {
    ...config.extra,
    eas: { projectId: '0d754966-dd40-44e2-b113-96a02f9b098d' },
  },

  plugins: [
    'expo-router',
    [
      // Sets the Android notification icon/colour and, on iOS, the push
      // entitlement the OS requires before it will issue a device token.
      'expo-notifications',
      {
        icon: './assets/icon.png',
        color: '#E91E73',
      },
    ],
    [
      // iOS crashes outright if a permission is requested without a usage
      // string, so these are required, not cosmetic.
      'expo-image-picker',
      {
        photosPermission: 'HeartLink uses your photos so you can add a profile picture.',
        cameraPermission: 'HeartLink uses your camera so you can take a profile picture.',
      },
    ],
    [
      // Without this the prebuilt splash is blank white on both platforms: the
      // generated iOS storyboard carried constraints pointing at an image view
      // that was never created, and there was no SplashScreenLogo image set for
      // them to point at.
      'expo-splash-screen',
      {
        image: './assets/splash-icon.png',
        imageWidth: 200,
        resizeMode: 'contain',
        backgroundColor: '#2E1240',
        dark: {
          image: './assets/splash-icon.png',
          backgroundColor: '#16051F',
        },
      },
    ],
  ],
});
