import { ExpoConfig, ConfigContext } from 'expo/config';

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'HeartLink',
  slug: 'heartlink',
  version: '0.0.1',
  orientation: 'portrait',
  scheme: 'heartlink',
  userInterfaceStyle: 'automatic',
  newArchEnabled: true,

  // Generated by scripts/generate-brand-assets.mjs. Opaque square: iOS applies
  // its own squircle mask and renders black through any transparency.
  icon: './assets/icon.png',

  ios: {
    supportsTablet: true,
    bundleIdentifier: 'com.heartlink.app',
    infoPlist: {
      // Device testing points EXPO_PUBLIC_API_BASE_URL at the dev machine's LAN
      // address. Since iOS 14 the first connection to a local address raises a
      // permission prompt, and a prompt with no usage string is denied outright
      // - which surfaces only as fetch() failing, with no dialog to explain it.
      NSLocalNetworkUsageDescription:
        'HeartLink connects to the development API running on your local network.',
    },
  },

  // Expo's web export only picks up a favicon when it is named here.
  web: {
    favicon: './assets/favicon.png',
  },

  android: {
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      // Matches the iOS icon ground so the app reads the same on both.
      backgroundColor: '#FDF9F6',
    },
    package: 'com.heartlink.app',
  },


  // EAS project link. Written by hand because `eas init` cannot edit a dynamic
  // (.ts) config; spread `config.extra` first so expo-router's own `extra`
  // survives rather than being replaced.
  extra: {
    ...config.extra,
    eas: { projectId: '0d754966-dd40-44e2-b113-96a02f9b098d' },
  },

  plugins: [
    'expo-router',
    [
      // React Native 0.76 pins Kotlin 1.9.24 on the Gradle classpath, while the
      // Expo template's default is 1.9.25. expo-modules-core picks its Compose
      // compiler from the template's number, so the two disagree and the
      // Android build dies on "Compose Compiler 1.5.15 requires Kotlin 1.9.25".
      // Saying 1.9.24 out loud settles it on React Native's version.
      'expo-build-properties',
      {
        android: {
          kotlinVersion: '1.9.24',
        },
      },
    ],
    [
      // Sets the Android notification icon/colour and, on iOS, the push
      // entitlement the OS requires before it will issue a device token.
      'expo-notifications',
      {
        // Android keeps only the alpha of a notification icon, so this is a
        // white silhouette; the full-colour icon arrived as a white blob.
        icon: './assets/notification-icon.png',
        color: '#E91E73',
      },
    ],
    [
      // iOS crashes outright if a permission is requested without a usage
      // string, so these are required, not cosmetic.
      'expo-image-picker',
      {
        photosPermission: 'HeartLink uses your photos so you can add a profile picture.',
        cameraPermission: 'HeartLink uses your camera so you can take a profile picture.',
      },
    ],
    [
      // Without this the prebuilt splash is blank white on both platforms: the
      // generated iOS storyboard carried constraints pointing at an image view
      // that was never created, and there was no SplashScreenLogo image set for
      // them to point at.
      //
      // The two platforms get different artwork because they can show different
      // things. iOS renders a launch storyboard, which can hold a full screen
      // image; Android 12 and up hand the splash to the platform's own API,
      // which draws one centred icon on a flat colour and nothing else. Sending
      // the tall artwork to Android would only crop it to a circle.
      //
      // The ground is the brand page colour on both, matching the artwork's own
      // ground and the first screen behind it, so the splash has no seam on the
      // way in or out. Dark mode reuses the light images deliberately: the
      // artwork is light by design, and the old dark override only meant a
      // purple flash on dark-mode devices.
      'expo-splash-screen',
      {
        backgroundColor: '#FDF9F6',
        dark: { backgroundColor: '#FDF9F6' },
        ios: {
          // Fitted, not cropped: the artwork meets the left and right edges of a
          // phone, and the band it leaves above and below is the same cream as
          // the image, so it reads full-bleed while nothing is cut off - on a
          // tablet as well, where filling would eat the tagline.
          image: './assets/heartlink-splash.png',
          resizeMode: 'contain',
          // Without this the plugin squashes the artwork into a centred 100pt
          // square. It is the only prop that pins the image view to all four
          // edges of the storyboard and copies the file at its full resolution,
          // which is what full-screen artwork needs; the `_legacy` name is about
          // matching the pre-SDK-50 layout, not deprecation.
          enableFullScreenImage_legacy: true,
          dark: { image: './assets/heartlink-splash.png' },
        },
        android: {
          // The mark, inset far enough to survive the circular mask Android 12
          // crops the splash icon with.
          image: './assets/splash-icon.png',
          imageWidth: 180,
          resizeMode: 'contain',
          dark: { image: './assets/splash-icon.png' },
        },
      },
    ],
  ],
});
